# Generated by Django 3.0.4 on 2020-03-19 12:12

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=48513294634, max_length=12)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Max 15 linijek', max_length=3000)),
                ('image', models.ImageField(upload_to='media')),
                ('section', models.CharField(choices=[('bathroom', 'łazienka'), ('kitchen', 'kuchnia'), ('closet', 'szafy'), ('beds', 'łóżka'), ('other', 'inne'), ('back', 'zaplecze')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', embed_video.fields.EmbedVideoField()),
                ('description', models.TextField(help_text='Max 15 linijek', max_length=3000)),
            ],
        ),
    ]
