# Generated by Django 3.0.4 on 2020-03-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='Max 15 linijek', max_length=3000, null=True),
        ),
    ]
