# Generated by Django 3.0.4 on 2020-03-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0002_auto_20200320_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='background',
            field=models.ImageField(upload_to='bcg'),
        ),
    ]
